### ISSUE TITLE
Error while downloading hmmdata using piggyback

### ISSUE THREAD

**Issue by hites77** [ukaraoz/microtrait#1]
Following error occur while i ran the command: 
piggyback::pb_download("hmm.tar.gz",repo = "ukaraoz/test",dest = file.path(.libPaths(),"microtrait", "extdata"))

Error:
Error in `$<-.data.frame`(`*tmp*`, "dest", value = c("/usr/local/lib/R/site-library/microtrait/extdata",  :
  replacement has 3 rows, data has 0
In addition: Warning messages:
1: In get_token() : Using default public GITHUB_TOKEN.
                     Please set your own token
2: In piggyback::pb_download("hmm.tar.gz", repo = "ukaraoz/test", dest = file.path(.libPaths(),  :
  file(s) hmm.tar.gz not found in repo ukaraoz/test

**Comment by cliffbueno** [comment]
I got a similar error after running prep.hmmmodels()

Error in value[[3L]](cond) : 
  Cannot access release data for repository ukaraoz/test. Check that you have set a GITHUB_TOKEN and that at least one release on your GitHub repository page.
In addition: Warning message:
In get_token() : Using default public GITHUB_TOKEN.
                     Please set your own token

**Comment by deanpettinga** [comment]
hey @cliffbueno and @hites77,
I also was having an issue with `prep.hmmmodels()`. I got the following error:
```
Error: <rlib_error: GitHub PAT must have one of these forms:
  * 40 hexadecimal digits (older PATs)
  * A 'ghp_' prefix followed by 36 to 251 more characters (newer PATs)>
```

As it turns out, this is not an issue with the microTrait package. what you probably need to do is generate a new Personal Access Token (PAT) that conforms to the requirements listed in the error. I had to do the same thing because my GitHub password/token saved by R did not conform to these token formatting and complexity requirements. i followed the advice in this issue: [https://github.com/aaronpeikert/repro/issues/65](https://github.com/aaronpeikert/repro/issues/65), which solved my problem.

good luck!

**Comment by ukaraoz** [comment]
Hi, sorry it took a while to get to the bottom of this. After github changed the [authentication method](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/), the piggyback download function failed with .token=NULL option.
I took piggyback offline for now, and replaced it with a hard link to the hmm database.
